# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h5_write_flat <- function(data, fname) {
    invisible(.Call('_tgutil_h5_write_flat', PACKAGE = 'tgutil', data, fname))
}

h5_read_flat <- function(fname, datasets = NULL) {
    .Call('_tgutil_h5_read_flat', PACKAGE = 'tgutil', fname, datasets)
}

